#!/usr/bin/env sh
# vim:set expandtab shiftwidth=4 filetype=sh:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/nvim-config.git
# ::: :/.claude/hooks/block-bulk-read.sh
#
#

# PreToolUse on Read. Refuses the files that cost a great deal to read and
# tell you nothing for it.
#
# This is a hook rather than a `permissions.deny` rule, and the difference
# is the entire point. A `Read(...)` deny rule is not scoped to the Read
# tool: Claude Code recognises file-naming commands inside Bash and
# applies the rule to those as well. Denying `Read(/words.txt)` was tested
# here and also denied `head -3 words.txt`, `wc -l words.txt` and
# `ls -la words.txt`, which removes the cheap inspection that makes
# blocking the whole-file read reasonable in the first place. It blocks
# Edit and Write on the same path too.
#
# A hook matching `Read` blocks just as hard, since exit 2 stops the call
# before permission rules are evaluated and cannot be overridden by an
# allow rule, while leaving Bash completely alone and saying what to reach
# for instead.
#
# `bun.lock` is deliberately absent. It is large but occasionally wanted in
# earnest, and `grep` for the package in question is the right way into it:
# its trailing commas are not JSON, so `jq` cannot parse it.

set -u

input=$(cat)

file=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')
[ -n "$file" ] || exit 0

root=${CLAUDE_PROJECT_DIR:-}
[ -n "$root" ] || root=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
[ -n "$root" ] || exit 0

relative=${file#"$root"/}
[ "$relative" != "$file" ] || exit 0

case "$relative" in
    words.txt | words_alpha.txt)
        what='a raw wordlist'
        why='untracked and third-party-derived, kept only to regenerate spell/en.utf-8.spl with :mkspell'
        how='head, tail, wc -l or grep through Bash, none of which this hook touches'
        ;;
    spell/*.spl)
        what='a compiled binary spell file'
        why='generated by :mkspell from words.txt, and tracked only because the compiled form is what Neovim loads'
        how='file or wc -c if you need to confirm it is there; its contents are not legible text'
        ;;
    *)
        exit 0
        ;;
esac

# Reported live rather than written into this message, so the number
# cannot drift away from the file it describes.
bytes=$(wc -c <"$file" 2>/dev/null || echo 0)
if [ "$bytes" -ge 1048576 ]; then
    size="$((bytes / 1048576)) MiB"
else
    size="$((bytes / 1024)) KiB"
fi

printf '%s is %s, %s.\n\n' "$relative" "$what" "$size" >&2
printf 'Reading it whole spends a great deal of context and tells you\n' >&2
printf 'almost nothing: it is %s.\n\n' "$why" >&2
printf 'Use %s.\n' "$how" >&2

exit 2
